ToggleMuteHotkey:
- Alt
- Oem3

AutoConfigs:

- HotKey:
  - Control
  - Alt
  - Shift
  - Oem3
  Locations:
    Work-PluggedHeadphones:
    - D-Edge-Staff
    - D-Edge-Guest
    - ''

- HotKey:
  - Control
  - Alt
  - Oem3
  Locations:
    Work-UnpluggedHeadphones:
    - D-Edge-Staff
    - D-Edge-Guest
    - ''
    Home:
    - Nueva-Rezo
    - Nueva-Rezo-5g
    - Ext-Nueva-Rezo
    - Ext-Nueva-Rezo-5g

Configurations:
  Home:
    Strip[0].device.wdm: Microphone (Yeti X WoW Edition)
    Bus[0].device.wdm: Casque (WH-1000XM4 Stereo)
    Bus[0].Gain: 0
  Work-UnpluggedHeadphones:
    Strip[0].device.wdm: Réseau de microphones (Realtek(R) Audio)
    Bus[0].device.wdm: Casque (Q35 Stereo)
    Bus[0].Gain: 0
  Work-PluggedHeadphones:
    Strip[0].device.wdm: External Mic (Realtek(R) Audio)
    Bus[0].device.wdm: Realtek HD Audio 2nd output (Realtek(R) Audio)
    Bus[0].Gain: -12

Defaults:
  Strip[0].A1: 0
  Strip[0].B1: 1
  Strip[1].device.wdm: ''
  Strip[1].A1: 0
  Strip[1].B1: 0
  Strip[2].device.wdm: CABLE Output (VB-Audio Virtual Cable)
  Strip[2].A1: 1
  Strip[2].B1: 0
  Bus[1].device.wdm: ''
  Bus[2].device.wdm: ''

On:
  Strip[0].Mute: 0
  Strip[1].Mute: 0
  Strip[2].Gain: -22

Off:
  Strip[0].Mute: 1
  Strip[1].Mute: 1
  Strip[2].Gain: 0

CheckIsOff:
  Strip[0].Mute: 1
  Strip[1].Mute: 1
